{"uuid": "a35aef6d-79eb-4ebb-bda3-776822f82a3b", "children": ["2bd3ef69-2354-4165-bf66-582092226c99"], "befores": [{"name": "fetch_userid", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='olympus-im-stage.phonepe.com', port=443): Max retries exceeded with url: /olympus/im/v1/auth/login (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x102dc90a0>: Failed to resolve 'olympus-im-stage.phonepe.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "trace": "  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/conftest.py\", line 57, in fetch_userid\n    return get_userid()\n           ^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/conftest.py\", line 44, in get_userid\n    fetch_token = token_generate()\n                  ^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/Utilities/utils.py\", line 22, in token_generate\n    send_request = requests.post(url, headers=olympus_header, json=olympus_payload)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1750908613485, "stop": 1750908613505}], "start": 1750908613485, "stop": 1750908613570}